[workspace]
members = [
    "components",
    "error",
    "migration",
    "pingora",
    "server",
    "service",
    "service-api",
    "switchgear",
    "testing"
]

resolver = "2"

[workspace.package]
version = "0.1.26"
edition = "2024"
rust-version = "1.97"

[workspace.dependencies]
switchgear-components = { version = "0.1.26", path = "components" }
switchgear-error = { version = "0.1.26", path = "error" }
switchgear-migration = { version = "0.1.26", path = "migration" }
switchgear-pingora = { version = "0.1.26", path = "pingora" }
switchgear-service = { version = "0.1.26", path = "service" }
switchgear-service-api = { version = "0.1.26", path = "service-api" }
switchgear-testing = { version = "0.1.26", path = "testing" }
secrecy = { version = "0.10", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "registry", "tracing-log"] }
tracing-ecs-formatter = { version = "3", default-features = false, features = ["opentelemetry"] }

[profile.release]
codegen-units = 1
lto = true
panic = 'abort'
strip = true

