@startuml
title PingoraLnBalancer Trait Dependencies

class PingoraLnBalancer<S,P,M,B>

package "lnurl-balancer-service" <<Rectangle>> {
  interface LnBalancer {
    +get_invoice()
    +health()
  }
  
  interface LnBalancerBackgroundServices {
    +run_continuous_health_check()
  }
  
  interface LnClientPool {
    +get_invoice()
    +get_metrics()
    +health()
    +connect()
  }
  
  interface LnMetricsCache {
    +get()
    +update()
  }
  
  interface BackoffProvider {
    +get_backoff()
  }
}

package "pingora-load-balancing" <<External>> {
  interface BackendSelection {
    +iter()
  }
  
  interface BackendIter
}

' Implementations
PingoraLnBalancer ..|> LnBalancer : implements
PingoraLnBalancer ..|> LnBalancerBackgroundServices : implements

' Generic constraints
PingoraLnBalancer --> BackendSelection : "S"
PingoraLnBalancer --> LnClientPool : "P"
PingoraLnBalancer --> LnMetricsCache : "M"
PingoraLnBalancer --> BackoffProvider : "B"
BackendSelection::Iter --> BackendIter : implements

@enduml