# This section is for x86, no changes here.
[target.x86_64-unknown-linux-musl]
linker = "/opt/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-lstdc++"]

# --- MODIFY THIS SECTION FOR ARM ---
[target.aarch64-unknown-linux-musl]
# Use the musl cross-compiler as the linker
linker = "/opt/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-lstdc++"]

[env]
CC_x86_64_unknown_linux_musl = "/opt/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc"
CXX_x86_64_unknown_linux_musl = "/opt/x86_64-linux-musl-cross/bin/x86_64-linux-musl-g++"
AR_x86_64_unknown_linux_musl = "/opt/x86_64-linux-musl-cross/bin/x86_64-linux-musl-ar"
CC_aarch64_unknown_linux_musl = "/opt/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc"
CXX_aarch64_unknown_linux_musl = "/opt/aarch64-linux-musl-cross/bin/aarch64-linux-musl-g++"
AR_aarch64_unknown_linux_musl = "/opt/aarch64-linux-musl-cross/bin/aarch64-linux-musl-ar"