name: Branch Protection CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container: bitshock/linux-musl-rust:1.90.0
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        run: rustup default 1.90.0

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Run unit tests
        run: cargo test --lib --verbose