name: Branch Protection CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_HOME: /github/home/.cargo
  CARGO_TARGET_DIR: /github/home/target

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci-rust:latest
      options: -v /var/run/docker.sock:/var/run/docker.sock --dns 127.0.0.11 --dns 8.8.8.8
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - uses: actions/checkout@v4

      - name: Start Docker Compose services
        run: |
          cd testing
          nohup /bin/sh -c 'docker compose up -d --build --wait; touch ./compose-ready' > compose.log 2>&1 &
          cd ..

      - name: Cache cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            /github/home/.cargo/registry/index/
            /github/home/.cargo/registry/cache/
            /github/home/.cargo/git/db/
            /github/home/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Check formatting
        if: false
        run: cargo fmt -- --check

      - name: Run clippy
        if: false
        run: cargo clippy -- -D warnings

      - name: Run unit tests
        if: false
        run: |
          cargo test --lib --bins

      - name: Compile integration tests
        run: |
          cargo test --test discovery --no-run
          cargo test --test offer --no-run

      - name: Wait for integration tests services
        run: |
          cd testing

          MAX_WAIT=300
          ELAPSED=0
          while [ ! -f ./compose-ready ] && [ $ELAPSED -lt $MAX_WAIT ]; do
            docker compose ps --format "table {{.Service}}\t{{.Status}}"
            sleep 1
            ELAPSED=$((ELAPSED + 1))
          done

          if [ ! -f ./compose-ready ]; then
            echo "Docker compose did not complete in ${MAX_WAIT}s"
            cat ./compose.log || true
            exit 1
          fi
                    
          . ./.env && docker network connect $SERVICES_NETWORK_NAME $(hostname)
          cd ..

      - name: Run integration tests
        run: |
          cp testing/.env .
          cargo test --test discovery
          cargo test --test offer
#          cargo test --test ln
#          cargo test --test features

      - name: Stop Docker Compose services
        if: always()
        run: docker compose -f testing/docker-compose.yml down -v